### ISSUE TITLE
Installing from pip won't work because there is no entry point

### ISSUE THREAD

**Issue by Dvd-Znf** [Dvd-Znf/monero-api-cli#1]
Currently installing from pip like this: `pip install monero-api-cli` will not work because there is no entry point specified in `pyproject.toml`

**Comment by Dvd-Znf** [comment]
Setuptools docs: https://setuptools.pypa.io/en/latest/userguide/entry_point.html
Maybe something like this would work:
``` toml
[project.scripts]
monero-api-cli = "monero-api-cli:__main__"
```
